---
version: 2
jobs:
  build:
    working_directory: ~/almost_ninja_web
    docker:
      - image: circleci/ruby:2.5.1
        environment:
          PGHOST: localhost
          PGUSER: almost_ninja_web
          RAILS_ENV: test
      - image: postgres:9.5
        environment:
          POSTGRES_USER: almost_ninja_web
          POSTGRES_DB: almost_ninja_web_test
          POSTGRES_PASSWORD: almost_ninja_web
    steps:
      - checkout
      # Restore Cached Dependencies
      - type: cache-restore
        name: Restore bundle cache
        key: almost-ninja-web-{{ checksum "Gemfile.lock" }}

      # Bundle install dependencies
      - run: bundle install --path vendor/bundle

      # Cache Dependencies
      - type: cache-save
        name: Store bundle cache
        key: almost-ninja-web-{{ checksum "Gemfile.lock" }}
        paths:
          - vendor/bundle

      # So we can wait for postgres to be ready
      - run: dockerize -wait tcp://localhost:5432 -timeout 1m

      # Run DB Setup
      - run: bundle exec rake db:setup
      # Run the tests
      - run: bundle exec rake
