---
version: 2
jobs:
  build:
    working_directory: ~/almost_ninja_web
    docker:
      - image: circleci/ruby:2.5-stretch-node-browsers-legacy
        environment:
          PGHOST: localhost
          PGUSER: almost_ninja_web
          RAILS_ENV: test
      - image: postgres:9.5
        environment:
          POSTGRES_USER: almost_ninja_web
          POSTGRES_DB: almost_ninja_web_test
          POSTGRES_PASSWORD: almost_ninja_web
    steps:
      - checkout

      # Restore Cached Dependencies
      - type: cache-restore
        name: Restore bundle cache
        key: almost-ninja-web-{{ checksum "Gemfile.lock" }}

      # Bundle install dependencies
      - run: bundle install --path vendor/bundle

      # Cache Dependencies
      - type: cache-save
        name: Store bundle cache
        key: almost-ninja-web-{{ checksum "Gemfile.lock" }}
        paths:
          - vendor/bundle

      # So we can wait for postgres to be ready
      - run: dockerize -wait tcp://localhost:5432 -timeout 1m

      # To precompile assets
      - type: cache-restore
        name: Restore yarn cache
        key: yarn-cache-v1-{{ checksum "yarn.lock" }}

      - run: yarn install --cache-folder ~/.cache/yarn
      - run: bundle exec rake webpacker:compile

      - type: cache-save
        name: Store yarn cache
        key: yarn-cache-v1-{{ checksum "yarn.lock" }}
        paths:
          - ~/.cache/yarn

      # Run DB Setup
      - run: bundle exec rake db:create
      - run: bundle exec rake db:migrate

      # Run the tests
      - run: bundle exec rake
